[build]
  command = "ng build --configuration production"
  publish = "dist/gremius/browser"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/"
  to = "/home"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200