// src/app/comisiones-anteriores/comisiones-anteriores.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-comisiones-anteriores',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './comisiones-anteriores.component.html',
  styleUrls: ['./comisiones-anteriores.component.css'],
})
export class ComisionesAnterioresComponent implements OnInit {
  expandedCard: string | null = null;

  comisiones = [
    {
      period: '25 de Octubre de 1982',
      secretarios: [
        { name: 'Domitilia Eduviges Rodríguez', role: 'Secretaria General' },
        { name: 'Susana Argentina Knoll', role: 'Secretaria Adjunta' },
        { name: 'Eduardo Clementi', role: 'Secretario Gremial' },
        { name: 'Ernesto Eduardo Bargero', role: 'Sec. Adm. y de Actas' },
        { name: 'Antonio Silvestre Segovia', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Adolfo Victoriano Bonachera', role: 'Sec. de Organización' },
      ],
      vocalesTitulares: [
        { name: 'Eduardo Edmundo Maturana', role: 'Vocal Titular' },
        { name: 'Silvia Graciela López', role: 'Vocal Titular' },
        { name: 'Osvaldo Orlando Abeldaño', role: 'Vocal Titular' },
        { name: 'Nelly Blanca Martínez', role: 'Vocal Titular' },
      ],
      vocalesSuplentes: [
        { name: 'Hilda del Carmen Mansilla', role: 'Vocal Suplente' },
        { name: 'Dina Battaglia', role: 'Vocal Suplente' },
        { name: 'Hernán José Huenchur', role: 'Vocal Suplente' },
      ],
      revisoresCuentas: [
        { name: 'Nora Violeta Saldivia', role: 'Miembro Titular' },
        { name: 'José Ramón Torres', role: 'Miembro Suplente' },
      ],
    },
    {
      period: '15 de Noviembre de 1984',
      secretarios: [
        { name: 'Silvia Graciela López', role: 'Secretaria General' },
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria Adjunta' },
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Gremial' },
        { name: 'Adriana Rosa Dileva', role: 'Sec. Adm. y de Actas' },
        { name: 'Domingo Enrique Urbieta', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'María Amalia Díaz', role: 'Vocal Titular' },
        { name: 'Patricia María Aranda', role: 'Vocal Titular' },
        { name: 'Marisa Rosana Arteaga', role: 'Vocal Titular' },
        { name: 'Domingo Enrique Urbieta', role: 'Vocal Titular' },
      ],
    },
    {
      period: '14 de Noviembre de 1984 (Provisoria)',
      secretarios: [
        { name: 'Patricia María Aranda', role: 'Secretaria General' },
        { name: 'Mirta Susana Oñate', role: 'Secretaria Adjunta' },
        { name: 'Teresita del Carmen Oñate', role: 'Secretaria Gremial' },
        { name: 'Ruth Elizabeth Figueroa', role: 'Sec. Adm. y de Actas' },
        { name: 'Domingo Enrique Urbieta', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'María Teresa Núñez', role: 'Vocal Titular' },
      ],
    },
    {
      period: '20 de Diciembre de 1984',
      secretarios: [
        { name: 'Silvia Graciela López', role: 'Secretaria General' },
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria Adjunta' },
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Gremial' },
        { name: 'Hilda del Carmen Cárdenas', role: 'Sec. Adm. y de Actas' },
        { name: 'Clara Alicia Navarro', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'María Arteaga', role: 'Vocal Titular' },
        { name: 'Alfredo Frasch', role: 'Vocal Titular' },
        { name: 'Adriana Dileva', role: 'Vocal Titular' },
        { name: 'Hilda Mansilla', role: 'Vocal Titular' },
      ],
      vocalesSuplentes: [
        { name: 'Patricia González', role: 'Vocal Suplente' },
        { name: 'María Amalia Díaz', role: 'Vocal Suplente' },
        { name: 'Mario Rosales', role: 'Vocal Suplente' },
        { name: 'Ramón Castillo', role: 'Vocal Suplente' },
      ],
    },
    {
      period: '5 de Junio de 1986',
      secretarios: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria General' },
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Adjunto' },
        { name: 'Marisa Rosana Arteaga', role: 'Secretaria Gremial' },
        { name: 'Adriana Rosa Dileva', role: 'Sec. Adm. y de Actas' },
        { name: 'Hilda del Carmen Cárdenas', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'Patricia González', role: 'Vocal Titular' },
        { name: 'María Amalia Díaz', role: 'Vocal Titular' },
        { name: 'Mario Martín Rosales', role: 'Vocal Titular' },
        { name: 'Ramón Roberto Castillo', role: 'Vocal Titular' },
      ],
    },
    {
      period: '19 de Diciembre de 1986 (Provisoria)',
      secretarios: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria General' },
        { name: 'María Rosa Arteaga', role: 'Secretaria Adjunta' },
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Gremial' },
        { name: 'Adriana Rosa Dileva', role: 'Sec. Adm. y de Actas' },
        { name: 'María Teresa Núñez', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'Sergio Omar Otero', role: 'Vocal Titular' },
        { name: 'Nidia Martha Basso', role: 'Vocal Titular' },
        { name: 'Eduardo Edmundo Maturana', role: 'Vocal Titular' },
        { name: 'Carmen Virginia Padros', role: 'Vocal Titular' },
      ],
      vocalesSuplentes: [
        { name: 'Gloria Haydee Vázquez', role: 'Vocal Suplente' },
        { name: 'Guido Rubén Vera', role: 'Vocal Suplente' },
        { name: 'Leonor Hilda Vera', role: 'Vocal Suplente' },
        { name: 'Eduardo David Gómez', role: 'Vocal Suplente' },
      ],
    },
    {
      period: '21 de Diciembre de 1988',
      secretarios: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria General' },
        { name: 'Emilio Eduardo Aybar', role: 'Secretario Adjunto' },
        { name: 'Alfonso Victoriano Lobo', role: 'Secretario Gremial' },
        { name: 'Ana María Vivanco', role: 'Sec. Adm. y de Actas' },
        { name: 'Nelly Blanca Martínez', role: 'Sec. Finanzas y Estadísticas' },
      ],
      vocalesTitulares: [
        { name: 'María Susana Grabas', role: 'Vocal Titular' },
        { name: 'Silvia Cistina Reinte', role: 'Vocal Titular' },
        { name: 'José Francisco Ramírez', role: 'Vocal Titular' },
        { name: 'Eduardo Edmundo Maturana', role: 'Vocal Titular' },
      ],
      vocalesSuplentes: [
        { name: 'Julio Santos Caprio', role: 'Vocal Suplente' },
        { name: 'Liliana Judith Romero', role: 'Vocal Suplente' },
        { name: 'Leonor Hilda Romero', role: 'Vocal Suplente' },
        { name: 'Nilda Beatriz García', role: 'Vocal Suplente' },
      ],
    },
    {
      period: '15 de Diciembre de 1990',
      secretarios: [
        { name: 'María Rosana Arteaga', role: 'Secretaria General' },
        { name: 'Carlos Amato', role: 'Secretario Adjunto' },
        { name: 'Juan Carlos Cardinali', role: 'Secretario Gremial' },
        { name: 'Francisco Ramírez', role: 'Sec. Adm. y de Actas' },
        { name: 'Jorge Sabella', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Francisco Gómez', role: 'Sec. de Organización' },
        { name: 'Roberto Hornus', role: 'Sec. de Prensa y Difusión' },
        { name: 'Jorge Contreras', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Mónica García', role: 'Sec. de Acción Social' },
        { name: 'Graciela Schettino', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Adjunto Suplente' },
        { name: 'Dabiel Pessolano', role: 'Secretario Gremial Suplente' },
        { name: 'Mirna Hudson', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Héctor López', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Gustavo Antecao', role: 'Sec. de Organización Suplente' },
        { name: 'Rosa Elena Barros', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Rita Rivera', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Liliana de la Fuente', role: 'Sec. de Acción Social Suplente' },
        { name: 'Margarita Palavecino', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Jorge Contreras', role: 'Titular' },
        { name: 'Ismael Ramón Machuca', role: 'Titular' },
        { name: 'Mario Cichinelli', role: 'Suplente' },
        { name: 'Alberto González', role: 'Suplente' },
      ],
    },
    {
      period: '15 de Diciembre de 1993',
      secretarios: [
        { name: 'Juan Carlos Cardinali', role: 'Secretario General' },
        { name: 'Ismael Ramón Machuca', role: 'Secretario Adjunto' },
        { name: 'Nelly Blanca Martínez', role: 'Secretaria Gremial' },
        { name: 'Ernesto Rodolfo Regueira', role: 'Sec. Adm. y de Actas' },
        { name: 'Héctor Hugo Lanzetti', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Mario Alejandro Moreno', role: 'Sec. de Organización' },
        { name: 'Carlos Antonio Mansilla', role: 'Sec. de Prensa y Difusión' },
        { name: 'José Luis Brito', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Antonio Ernesto Quiroga', role: 'Sec. de Acción Social' },
      ],
      vocalesSuplentes: [
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Adjunto Suplente' },
        { name: 'José Luis Quinteros', role: 'Secretario Gremial Suplente' },
        { name: 'Alicia del Carmen Figueroa', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Ramón Roberto Castillo', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Silvia Cristina Riente', role: 'Sec. de Organización Suplente' },
        { name: 'Héctor Paul Fermani', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Ricardo Milton Moreno', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Marcelina Gumersinda Ochoa', role: 'Sec. de Acción Social Suplente' },
        { name: 'Margarita Azucena Palavecino', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'María Teresa Núñez', role: 'Titular' },
        { name: 'Ismael Ramón Machuca', role: 'Titular' },
        { name: 'Héctor Raúl Llanos', role: 'Suplente' },
        { name: 'Iris Jovita Vivar', role: 'Suplente' },
      ],
    },
    {
      period: '15 de Noviembre de 1995',
      secretarios: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria General' },
        { name: 'Ramón Hipólito Rasijdo', role: 'Secretario Adjunto' },
        { name: 'Alicia Inés Troncoso', role: 'Secretaria Gremial' },
        { name: 'Silvia Mónica Álvarez', role: 'Sec. Adm. y de Actas' },
        { name: 'Miguel Armando Ramírez', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Adolfo Victoriano Bonachera', role: 'Sec. de Organización' },
        { name: 'Ana Elisa Medina', role: 'Sec. de Prensa y Difusión' },
        { name: 'Carlos Alberto Vargas', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'María Teresa Núñez', role: 'Sec. de Acción Social' },
        { name: 'Dora Azucena Córdoba', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Rubén Segundo Sepúlveda', role: 'Secretario Adjunto Suplente' },
        { name: 'José Raúl Quinteros', role: 'Secretario Gremial Suplente' },
        { name: 'Alicia del Carmen Figueroa', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Ramón Alberto Castillo', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Silvia Cristina Riente', role: 'Sec. de Organización Suplente' },
        { name: 'Héctor Raúl Fermani', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Ricardo Milton Moreno', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Marcelina Gumersinda Ochoa', role: 'Sec. de Acción Social Suplente' },
        { name: 'Margarita Azucena Palavecino', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Titular' },
        { name: 'Miguel Armando Ramírez', role: 'Titular' },
        { name: 'Nilda Beatriz García', role: 'Suplente' },
        { name: 'Alicia Inés Troncoso', role: 'Suplente' },
      ],
    },
    {
      period: '3 de Agosto de 1998',
      secretarios: [
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria General' },
        { name: 'Carlos Marcelo Ballester', role: 'Secretario Adjunto' },
        { name: 'Vivian Luz Teppa', role: 'Secretaria Gremial' },
        { name: 'Nidia Martha Basso', role: 'Sec. Adm. y de Actas' },
        { name: 'Néstor Omar Gallardo', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Miguel Armando Ramírez', role: 'Sec. de Organización' },
        { name: 'Alicia del Carmen Figueroa', role: 'Sec. de Prensa y Difusión' },
        { name: 'César Armando Díaz Estevez', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Silvia Mónica Álvarez', role: 'Sec. de Acción Social' },
        { name: 'María Teresa Núñez', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Juan Edmundo Zamora', role: 'Secretario Adjunto Suplente' },
        { name: 'Mabel Noemí Castagno', role: 'Secretaria Gremial Suplente' },
        { name: 'Antonio Silvestre Segovia', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Dais Myrian Sotomayor', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Luis Bernardo Knoll', role: 'Sec. de Organización Suplente' },
        { name: 'Susana Martínez', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Mabel Yolanda Acosta', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Ernesto Luis Ioras', role: 'Sec. de Acción Social Suplente' },
        { name: 'Juan José Ortega', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'César Armando Díaz Estevez', role: 'Titular' },
        { name: 'Rubén Armando Viusen', role: 'Titular' },
        { name: 'Elsa María Álvarez', role: 'Suplente' },
        { name: 'Colombino Ramírez', role: 'Suplente' },
      ],
    },
    {
      period: '3 de Agosto de 2001',
      secretarios: [
        { name: 'María Teresa Núñez', role: 'Secretaria General' },
        { name: 'Juan Eduardo Zamora', role: 'Secretario Adjunto' },
        { name: 'Horacio Oscar Gómez', role: 'Secretario Gremial' },
        { name: 'Hugo Pablo Agüero', role: 'Sec. Adm. y de Actas' },
        { name: 'Néstor Omar Gallardo', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Roberto Nicolás Kornuta', role: 'Sec. de Organización' },
        { name: 'Susana Martínez', role: 'Sec. de Prensa y Difusión' },
        { name: 'Olegario Eusebio Solorza', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Nilda Beatriz García', role: 'Sec. de Acción Social' },
        { name: 'Mabel Yolanda Acosta', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Alicia del Carmen Figueroa', role: 'Secretaria Adjunta Suplente' },
        { name: 'Omar Ernesto Pichipil', role: 'Secretario Gremial Suplente' },
        { name: 'José Guillermo Perea', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Francisca Antonio Igor', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Luis Alberto Godoy', role: 'Sec. de Organización Suplente' },
        { name: 'Claudio Horacio Sepúlveda', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Miguel Ángel Chaves', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Oscar Augusto Bode', role: 'Sec. de Acción Social Suplente' },
        { name: 'Zulema Villalba', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Horacio Oscar Gómez', role: 'Titular' },
        { name: 'Jorge Eduardo Contreras', role: 'Titular' },
        { name: 'Rubén Armando Viusen', role: 'Suplente' },
        { name: 'Lucrecia Ramona Kanappe', role: 'Suplente' },
      ],
    },
    {
      period: '3 de Agosto de 2004',
      secretarios: [
        { name: 'Oscar Augusto Bode', role: 'Secretario General' },
        { name: 'Elsa Beatriz Capuchinelli', role: 'Secretaria Adjunta' },
        { name: 'Carlos Antonio Mansilla', role: 'Secretario Gremial' },
        { name: 'María Angélica Galich', role: 'Sec. Adm. y de Actas' },
        { name: 'Roberto Javier Hornus', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Jorge Eduardo Contreras', role: 'Sec. de Organización' },
        { name: 'Horacio Oscar Gómez', role: 'Sec. de Prensa y Difusión' },
        { name: 'Humberto Marcos Chalie', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Nora Beatriz de Diego', role: 'Sec. de Acción Social' },
        { name: 'César Armando Díaz Estevez', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Jorge Guillermo Rivarola', role: 'Secretario Adjunto Suplente' },
        { name: 'Francisca Antonia Igor', role: 'Secretario Gremial Suplente' },
        { name: 'José Guillermo Perea', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Juan Eduardo Zamora', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Luis Omar Gonzales', role: 'Sec. de Organización Suplente' },
        { name: 'Juan Manuel Berra', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Osvaldo Rubén Paiva', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Gustavo Javier Antecao', role: 'Sec. de Acción Social Suplente' },
        { name: 'Antonio Santiago Prieto', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Carlos Marcelo Ballester', role: 'Titular' },
        { name: 'Alicia del Carmen Figueroa', role: 'Titular' },
        { name: 'Olegario Eusebio Solorza', role: 'Suplente' },
        { name: 'Mónica del Carmen Suppo', role: 'Suplente' },
      ],
    },
    {
      period: '3 de Agosto de 2007',
      secretarios: [
        { name: 'Francisco Alfredo Gómez', role: 'Secretario General' },
        { name: 'Juan José Ortega', role: 'Secretario Adjunto' },
        { name: 'Horacio Oscar Gómez', role: 'Secretario Gremial' },
        { name: 'Norma Alicia Santillán', role: 'Sec. Adm. y de Actas' },
        { name: 'María Susana Grabas', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Alfonso Victoriano Lobo', role: 'Sec. de Organización' },
        { name: 'Julio César Stout', role: 'Sec. de Prensa y Difusión' },
        { name: 'Ana María Peralta', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Luis Osvaldo Calisto', role: 'Sec. de Acción Social' },
        { name: 'Mirna Susana Hudson', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Feliciano Alberto González', role: 'Secretario Adjunto Suplente' },
        { name: 'Gustavo Javier Antecao', role: 'Secretario Gremial Suplente' },
        { name: 'María Elena Ulloa', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Marta Angélica Zavala', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Ramón Alejandro Paolazzi', role: 'Sec. de Organización Suplente' },
        { name: 'Fernando Gabriel Amaya', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Elsa Haydee Pastori', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'José Manuel Urbieta', role: 'Sec. de Acción Social Suplente' },
        { name: 'Margarita Rita Cosme', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Francisco Alfredo Gómez', role: 'Titular' },
        { name: 'Susana Martínez', role: 'Titular' },
        { name: 'María Angélica Galich', role: 'Suplente' },
        { name: 'Patricia Marisol Wigand', role: 'Suplente' },
      ],
    },
    {
      period: '30 de Junio de 2010',
      secretarios: [
        { name: 'Francisco Alfredo Gómez', role: 'Secretario General' },
        { name: 'Juan José Ortega', role: 'Secretario Adjunto' },
        { name: 'Romina Mc Namara', role: 'Secretaria Gremial' },
        { name: 'Melania Pérez', role: 'Sec. Adm. y de Actas' },
        { name: 'Luis Osvaldo Calisto', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Horacio Gómez', role: 'Sec. de Organización' },
        { name: 'Julio César Stout', role: 'Sec. de Prensa y Difusión' },
        { name: 'Elsa Pastori', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Carolina Miro', role: 'Sec. de Acción Social' },
        { name: 'Mirna Susana Hudson', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Rubén Fernández', role: 'Secretario Adjunto Suplente' },
        { name: 'Alejandra Beroiz', role: 'Secretaria Gremial Suplente' },
        { name: 'Patricia Wigand', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Guillermo Ghio', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Rubén Viusen', role: 'Sec. de Organización Suplente' },
        { name: 'Horacio Loyola', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Martín Segovia', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Claudia Marino', role: 'Sec. de Acción Social Suplente' },
        { name: 'Isabel Giménez', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Francisco Alfredo Gómez', role: 'Titular' },
        { name: 'Alfonso Victoriano Lobo', role: 'Titular' },
        { name: 'Alejandro Paolazzi', role: 'Suplente' },
        { name: 'Enrique Taboada', role: 'Suplente' },
      ],
    },
    {
      period: '1 de Agosto de 2013',
      secretarios: [
        { name: 'Juan José Ortega', role: 'Secretario General' },
        { name: 'Alfonso Victoriano Lobo', role: 'Secretario Adjunto' },
        { name: 'Romina Mc Namara', role: 'Secretaria Gremial' },
        { name: 'María Verónica Levati', role: 'Sec. Adm. y de Actas' },
        { name: 'Diego Rubén Rosselli', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Ana Carolina Miro', role: 'Sec. de Organización' },
        { name: 'Silvia Valeria Gerez Bravo', role: 'Sec. de Prensa y Difusión' },
        { name: 'Héctor Horacio Loyola', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'María Alejandra Beroiz', role: 'Sec. de Acción Social' },
      ],
      vocalesSuplentes: [
        { name: 'Susana Ethel Gargiulo', role: 'Secretaria Adjunta Suplente' },
        { name: 'Alejandra Daniela Morales', role: 'Secretaria Gremial Suplente' },
        { name: 'Carola Renee Valderrama', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Daniel Adrián Vega', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Rubén Viusen', role: 'Sec. de Organización Suplente' },
        { name: 'Javier Lucas Calismonte', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Mirta Elizabeth Beltrán', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Fernando Horacio Abeldaño', role: 'Sec. de Acción Social Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Juan José Ortega', role: 'Titular' },
        { name: 'Eduardo Giménez', role: 'Titular' },
        { name: 'José Luis Britos', role: 'Suplente' },
        { name: 'Juan Franco Mascheroni', role: 'Suplente' },
      ],
    },
    {
      period: '1 de Agosto de 2016',
      secretarios: [
        { name: 'Francisco Alfredo Gómez', role: 'Secretario General' },
        { name: 'Rosa del Carmen Hindie', role: 'Secretaria Adjunta' },
        { name: 'María Verónica Levati', role: 'Secretario Gremial' },
        { name: 'Carola Renee Valderrama', role: 'Sec. Adm. y de Actas' },
        { name: 'Martín Díaz', role: 'Sec. Finanzas y Estadísticas' },
        { name: 'Oscar Huancq', role: 'Sec. de Organización' },
        { name: 'María José Butterfield', role: 'Sec. de Prensa y Difusión' },
        { name: 'Martín Segovia', role: 'Sec. de Cap. Lab. y Gremial' },
        { name: 'Guadalupe Judis', role: 'Sec. de Acción Social' },
        { name: 'Héctor Paez', role: 'Sec. de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Alejandro Paolazzi', role: 'Secretario Adjunto Suplente' },
        { name: 'Matías Abate', role: 'Secretario Gremial Suplente' },
        { name: 'Lionel Pedernera', role: 'Sec. Adm. y de Actas Suplente' },
        { name: 'Martín Vargas', role: 'Sec. Finanzas y Estadísticas Suplente' },
        { name: 'Jesús Sevilla', role: 'Sec. de Organización Suplente' },
        { name: 'Claudia Gunther', role: 'Sec. de Prensa y Difusión Suplente' },
        { name: 'Rubén Viusen', role: 'Sec. de Cap. Lab. y Gremial Suplente' },
        { name: 'Patricia Wigand', role: 'Sec. de Acción Social Suplente' },
        { name: 'Olegario Solorza', role: 'Sec. de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Francisco Alfredo Gómez', role: 'Titular' },
        { name: 'Ana Carolina Miro', role: 'Titular' },
        { name: 'Susana Gargiulo', role: 'Suplente' },
        { name: 'Rosa del Carmen Hindie', role: 'Suplente' },
      ],
    },
    {
      period: '1 de Agosto de 2019',
      secretarios: [
        { name: 'María Eugenia Bianchi Galich', role: 'Secretaria General' },
        { name: 'Noelia Marisel Vidal', role: 'Secretaria Adjunta' },
        { name: 'Pablo Sebastián Salcedo', role: 'Secretario Gremial' },
        { name: 'Gabriela Soledad Vera', role: 'Secretaria Administrativa y de Actas' },
        { name: 'Matías Exequiel Román', role: 'Secretario de Finanzas y Estadística' },
        { name: 'Marianela Raquel Contreras', role: 'Secretaria de Organización' },
        { name: 'Lucas Antonio Pachilla', role: 'Secretario de Prensa y Difusión' },
        { name: 'Diego Joaquín Federico Gaitán', role: 'Secretario de Capacitación Laboral y Gremial' },
        { name: 'Berta Mónica Julián', role: 'Secretaria de Acción Social' },
        { name: 'Noelia Soledad Laba', role: 'Secretaria de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Vacante', role: 'Secretario Adjunto Suplente' },
        { name: 'Libertad Zunilda Fraccarolli', role: 'Secretaria Gremial Suplente' },
        { name: 'Pedro Carlos Tula', role: 'Secretario Administrativo y de Actas Suplente' },
        { name: 'Mario Nicolás Ormeño', role: 'Secretario de Finanzas y Estadísticas Suplente' },
        { name: 'Tayhana Vanina López', role: 'Secretaria de Organización Suplente' },
        { name: 'Mirna Yanina Larrosa', role: 'Secretaria de Prensa y Difusión Suplente' },
        { name: 'Elsa Haydee Pastori', role: 'Secretaria de Capacitación Laboral y Gremial Suplente' },
        { name: 'Rosa Mercedes Gómez', role: 'Secretaria de Acción Social Suplente' },
        { name: 'Vacante', role: 'Secretario de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Rosa del Carmen Hindie', role: 'Titular' },
        { name: 'Juan Franco Mascheroni', role: 'Suplente' },
        { name: 'Claudia Susana Muñoz', role: 'Suplente' },
      ],
    },
    {
      period: '1 de Agosto de 2022',
      secretarios: [
        { name: 'María Alejandra Beroiz', role: 'Secretaria General' },
        { name: 'Juan Franco Mascheroni', role: 'Secretario Adjunto' },
        { name: 'Adriana Isabel Nieto López', role: 'Secretaria Gremial' },
        { name: 'Ruth Eliette Ayala Vargas', role: 'Secretaria Administrativa y de Actas' },
        { name: 'Fernando Horacio Abeldaño', role: 'Secretario de Finanzas y Estadística' },
        { name: 'Aníbal Roberto Sosa', role: 'Secretario de Organización' },
        { name: 'Dana Kinter', role: 'Secretaria de Prensa y Difusión' },
        { name: 'Florencia Alejandra Ampuero Milostic', role: 'Secretaria de Capacitación Laboral y Gremial' },
        { name: 'Claudia Alejandra D’Ambrosio', role: 'Secretaria de Acción Social' },
        { name: 'Luis Alberto Quiroga', role: 'Secretario de Derechos Humanos' },
      ],
      vocalesSuplentes: [
        { name: 'Susana Ethel Gargiulo', role: 'Secretaria Adjunto Suplente' },
        { name: 'Marianela Raquel Contreras', role: 'Secretaria Gremial Suplente' },
        { name: 'Ramón Alejandro Paolazzi', role: 'Secretario Administrativo y de Actas Suplente' },
        { name: 'Héctor Ricardo Roberts', role: 'Secretario de Finanzas y Estadísticas Suplente' },
        { name: 'Edgar Armando Cippitelli', role: 'Secretario de Organización Suplente' },
        { name: 'Héctor Horacio Paez', role: 'Secretario de Prensa y Difusión Suplente' },
        { name: 'Fernando Ramón Opazo', role: 'Secretario de Capacitación Laboral y Gremial Suplente' },
        { name: 'Lionel Norberto Pedernera', role: 'Secretario de Acción Social Suplente' },
        { name: 'Mabel Alejandra Alonso', role: 'Secretaria de Derechos Humanos Suplente' },
      ],
      delegadosCongresales: [
        { name: 'Alejandra Beroiz', role: 'Titular' },
        { name: 'Romina Mc Namara', role: 'Titular' },
        { name: 'Mirna Larrosa', role: 'Suplente' },
        { name: 'Lorena Behm', role: 'Suplente' },
      ],
    },
  ];

  ngOnInit(): void {}

  toggleCard(period: string): void {
    this.expandedCard = this.expandedCard === period ? null : period;
  }

  isCardExpanded(period: string): boolean {
    return this.expandedCard === period;
  }

  getVocalesSuplentesTitulo(period: string): string {
  const match = period.match(/\d{4}/); // busca un año en el string
    if (match) {
      const year = parseInt(match[0], 10);
      return year >= 1990 ? 'Suplentes' : 'Vocales Suplentes';
    }
    return 'Vocales Suplentes'; // por defecto
  }
}